language: csharp
solution: Source/SharpAESCrypt.sln
dotnet: 2.2
install:
  - dotnet restore Source/SharpAESCrypt.sln
  - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner
script:
  - dotnet build -c Release Source/SharpAESCrypt.sln
  - dotnet test Unittest/Unittest.csproj --filter TestCategory=Bulk
  - dotnet test Unittest/Unittest.csproj --filter TestCategory!=Bulk
  - dotnet pack -c Release .\SharpAESCrypt.csproj -p:IsLibrary=true
  - dotnet pack -c Release .\SharpAESCrypt.csproj -p:IsLibrary=false
